author = "Franci Branda-Chen"
# baseURL = 'https://fbc101.github.io/hugo-mock-landing-page-domain-name/'
copyright = "Franci Branda-Chen"
title = "CrimeGuard"

timeZone = 'America/New_York'

theme = "hugo-bootstrap-theme"
